{'base_qs': <QuerySet [<EntsIntegerPropsValues: hydrogen atom.atomic number[0]=1>, <EntsIntegerPropsValues: methane.chemical formula[0]=None>, <EntsIntegerPropsValues: helium atom.atomic number[0]=2>, <EntsIntegerPropsValues: helium atom.period (atom peroperty)[0]=67>, <EntsIntegerPropsValues: helium atom.group (atom peroperty)[0]=68>, <EntsIntegerPropsValues: hydrogen atom.period (atom peroperty)[0]=67>, <EntsIntegerPropsValues: hydrogen atom.group (atom peroperty)[0]=66>]>,
 'cls': <class 'search_in_database.models.EntsIntegerPropsValues'>,
 'force_insert': False,
 'force_update': False,
 'forced_update': False,
 'meta': <Options for EntsIntegerPropsValues>,
 'non_pks': [<django.db.models.fields.related.ForeignKey: prop_eid>,
             <django.db.models.fields.IntegerField: drowid>,
             <django.db.models.fields.BigIntegerField: dvalue>,
             <django.db.models.fields.CharField: comments>],
 'pk_set': True,
 'pk_val': 74,
 'raw': False,
 'self': <EntsIntegerPropsValues: helium atom.atomic number[1]=2>,
 'update_fields': None,
 'updated': False,
 'using': 'default',
 'values': [(<django.db.models.fields.related.ForeignKey: prop_eid>, None, 19),
            (<django.db.models.fields.IntegerField: drowid>, None, 1),
            (<django.db.models.fields.BigIntegerField: dvalue>, None, 2),
            (<django.db.models.fields.CharField: comments>, None, None)]}

pp locals()
{'ModelForm': <class 'django.forms.widgets.EntsIntegerPropsValuesForm'>,
 'add': False,
 'extra_context': None,
 'form': <EntsIntegerPropsValuesForm bound=True, valid=True, fields=(prop_owner_eid;prop_eid;drowid;dvalue;comments)>,
 'form_url': '',
 'form_validated': True,
 'formsets': [],
 'inline_instances': [],
 'model': <class 'search_in_database.models.EntsIntegerPropsValues'>,
 'new_object': <EntsIntegerPropsValues: helium atom.atomic number[1]=2>,
 'obj': <EntsIntegerPropsValues: helium atom.atomic number[1]=2>,
 'object_id': '74$19$0',
 'opts': <Options for EntsIntegerPropsValues>,
 'request': <WSGIRequest: POST '/admin/search_in_database/entsintegerpropsvalues/74$19$0/change/'>,
 'self': <search_in_database.admin.EntityRelationEntityAdmin object at 0x000001E8DB92FEF0>,
 'to_field': None}

{'ModelForm': <class 'django.forms.widgets.EntsIntegerPropsValuesForm'>,
 'add': False,
 'extra_context': None,
 'form': <EntsIntegerPropsValuesForm bound=True, valid=True, fields=(prop_owner_eid;prop_eid;drowid;dvalue;comments)>,
 'form_url': '',
 'form_validated': True,
 'formsets': [],
 'inline_instances': [],
 'model': <class 'search_in_database.models.EntsIntegerPropsValues'>,
 'new_object': <EntsIntegerPropsValues: helium atom.atomic number[1]=2>,
 'obj': <EntsIntegerPropsValues: helium atom.atomic number[1]=2>,
 'object_id': '74$19$0',
 'opts': <Options for EntsIntegerPropsValues>,
 'request': <WSGIRequest: POST '/admin/search_in_database/entsintegerpropsvalues/74$19$0/change/'>,
 'self': <search_in_database.admin.EntityRelationEntityAdmin object at 0x000001E8DB92FEF0>,
 'to_field': None}


 {'ModelForm': <class 'django.forms.widgets.EntsIntegerPropsValuesForm'>,
 'add': False,
 'extra_context': None,
 'form': <EntsIntegerPropsValuesForm bound=True, valid=True, fields=(prop_owner_eid;prop_eid;drowid;dvalue;comments)>,
 'form_url': '',
 'form_validated': True,
 'formsets': [],
 'inline_instances': [],
 'model': <class 'search_in_database.models.EntsIntegerPropsValues'>,
 'new_object': <EntsIntegerPropsValues: lithium.atomic number[0]=2>,
 'obj': <EntsIntegerPropsValues: lithium.atomic number[0]=2>,
 'object_id': '74$19$0',
 'opts': <Options for EntsIntegerPropsValues>,
 'request': <WSGIRequest: POST '/admin/search_in_database/entsintegerpropsvalues/74$19$0/change/'>,
 'self': <search_in_database.admin.EntityRelationEntityAdmin object at 0x0000017C29DDD780>,
 'to_field': None}


 -> obj.save()
(Pdb) pp locals()
{'change': True,
 'form': <EntsIntegerPropsValuesForm bound=True, valid=True, fields=(prop_owner_eid;prop_eid;drowid;dvalue;comments)>,
 'obj': <EntsIntegerPropsValues: lithium.atomic number[0]=2>,
 'request': <WSGIRequest: POST '/admin/search_in_database/entsintegerpropsvalues/74$19$0/change/'>,
 'self': <search_in_database.admin.EntityRelationEntityAdmin object at 0x0000027121BC5CF8>}
